[versions]
agp = "8.10.1"
startupruntime = "1.2.0"

[libraries]
startupruntime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupruntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

